name: Build
on: [push]
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: latest
          cache: true
          cache_dependency_path: package.json
      - run: pnpm build
      - run: pnpm exec puppeteer browsers install chrome
      - run: pnpm exec decktape --chrome-arg=--no-sandbox reveal resulting.html resulting.pdf
      - uses: actions/upload-artifact@v7
        with:
          name: presentation.html
          archive: false
          path: resulting.html
      - uses: actions/upload-artifact@v7
        with:
          name: presentation.pdf
          archive: false
          path: resulting.pdf